### ISSUE TITLE
Issue with calibre web db

### ISSUE THREAD

**Issue by shubhank-saxena** [abhilesh/self-hosted_docker_setups#1] opened 2021-09-30 16:47 UTC
Thank you so much for this amazing collection of docker-compose files!
While firing up calibre-web I am not able to locate the correct location of DB. Can you please help me out with that?
This is my docker-compose
```
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      # I had some issues with Google's OAuth login and hence added the following two lines
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
    volumes:
      - /srv/dev-disk-by-label-media/Files/AppData/Config/Calibre-Web:/config                   # Config directory (`app.db` is stored here)
      - /home/dietpi/Documents/Library:/books            # Data directory (All ebooks are stored here)
    ports:
      - 8083:8083
    restart: unless-stopped
```

**Comment by abhilesh** [comment] 2021-09-30 17:18
The database will be stored in an ```app.db``` file inside your ```/config``` directory, so you should be able to find it at ```/srv/dev-disk-by-label-media/Files/AppData/Config/Calibre-Web/app.db```

You can use a SQLite browser such as https://sqlitebrowser.org/ to check the contents of the database.

**Comment by shubhank-saxena** [comment] 2021-10-17 10:28
Thank you for that. But I am still not able to find the db to select here. I am sorry to bug you, but I am not at all able to figure out why I can't see the db :(

![Screenshot 2021-10-17 at 3 57 45 PM](https://user-images.githubusercontent.com/29003047/137623245-177c530c-556f-46d5-8662-b6de1717b0cd.png)

**Comment by abhilesh** [comment] 2021-10-18 16:40
Oh, for that step, try putting `/books` as the location of the Calibre Database in the setup step. That should work

**Comment by shubhank-saxena** [comment] 2021-10-18 17:11
It's throwing the following error after I put in `/books` as location
![Screenshot 2021-10-18 at 10 39 49 PM](https://user-images.githubusercontent.com/29003047/137776847-eba5fa97-1b77-48e8-8a8d-753c4e4985fb.png)

**Comment by abhilesh** [comment] 2021-10-18 17:13
Can you post the content of the entire log file here? I would like to see the last line of the log

**Comment by shubhank-saxena** [comment] 2021-10-18 17:14
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: books
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 39, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 752, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 413, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order,
File "/app/calibre-web/cps/db.py", line 679, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 685, in fill_indexpage_with_archived_books
randm = self.session.query(Books) \
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2711, in all
return self._iter().all()
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2846, in _iter
result = self.session.execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1689, in execute
result = conn._execute_20(statement, params or {}, execution_options)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
return connection._execute_clauseelement(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
ret = self._execute_context(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: books
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags
FROM books
WHERE (books.id NOT IN (SELECT 1 FROM (SELECT 1) WHERE 1!=1)) ORDER BY random()
LIMIT ? OFFSET ?]
[parameters: (4, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by abhilesh** [comment] 2021-10-18 17:20
According to https://github.com/janeczku/calibre-web/issues/1564, this should have been fixed in a previous release.
I'd recommend recreating the containers using ```docker-compose up -d --force-recreate```. See if the issue persists, if it does I will have to look deeper into it.

**Comment by shubhank-saxena** [comment] 2021-10-18 18:06
Tried the above method. Getting the same issue. Thank you so much for your help though!

**Comment by abhilesh** [comment] 2021-10-20 19:02
No problem. Are you starting out with an existing database or an empty one? I would recommend starting out with an empty database first to see if you can get the container running.

**Comment by shubhank-saxena** [comment] 2021-10-23 19:59
> No problem. Are you starting out with an existing database or an empty one? I would recommend starting out with an empty database first to see if you can get the container running.

Empty one. This is a completely fresh install. I have tried 2-3 times, and everytime I make sure that I delete all volume mounts as well

**Comment by abhilesh** [comment] 2021-12-14 15:15
Were you able to solve this? Another avenue that might be causing issues could be the permissions set on your database directories. Does docker have adequate permissions on the `/home/dietpi/Documents/Library` directory?

**Comment by shubhank-saxena** [comment] 2022-01-04 11:23
Yes. It finally worked. The docker permissions were good. The issue was PUID and PGID values. I learned that it is different for different users. Mine was 0 and 0

**Comment by abhilesh** [comment] 2022-01-07 01:01
Glad to hear that! Permission issues are often the cause, closing this now.

**Closed as completed by abhilesh** 2022-01-07 01:01 UTC
